### ISSUE TITLE
Merged blog post?

### ISSUE THREAD

**Issue by Msver** [iclr-blogposts/2025#201]
It seems like a blog post is merged into the main branch and now live on the official webpage:
https://iclr-blogposts.github.io/2025/blog/gradient-similarity-in-cnns-a-new-perspective-on-class-concept-representation/
The related pull request #200 was opened three days ago which is after the submission deadline. Is this a sample blog post because the contents do not seem to be a sample or something classic that is published before. Also the organizer @SchwinnL merged this into the main branch, is there a justified reason to do so?

**Comment by SchwinnL** [comment]
Hi,

there were some technical issues, which let to authors not being able to
merge their PR.
However, I should not have merged it into main! Thanks for letting us know.

Best,
Leo

Am Fr., 29. Nov. 2024 um 13:04 Uhr schrieb Msver ***@***.***>:

**Comment by Msver** [comment]
May I know why the PR needs merging? If it is a valid submission, the PR opens past the deadline and the outcome was advertised to be ~Jan 22nd. If it does not count as a valid submission then there is no further question for me.
